
#ifndef DIRECTRECEIVETASK_GENERATED_H_
#define DIRECTRECEIVETASK_GENERATED_H_


#include <stdio.h>
#include <pthread.h>


/******************************
 *  System generated code
 ******************************/

static void send(DirectReceiveTask this, Message data, int targetTaskID);
static void receive(DirectReceiveTask this);

//static void *run(void *PapaTaskRef);
static void *run(void *DirectReceiveTaskRef);
static void start(DirectReceiveTask this);

static void handle_BarMsg(DirectReceiveTask this, BarMsg barMsg);

// The DirectReceiveTask "class"
struct DirectReceiveTask {

	// private data members
	pthread_t threadRef;
	int taskID;

};


// The DirectReceiveTask "constructor"
unsigned int DirectReceiveTask_create(){

	DirectReceiveTask newRec = malloc(sizeof(struct DirectReceiveTask));
	if(newRec == NULL)
		FatalError("Cannot allocate memory in DirectReceiveTask_create");

	newRec->taskID = Comm->getNextTaskID();
	Comm->createMsgQ(newRec->taskID);

	int result = pthread_create( &(newRec->threadRef), NULL, run, (void *)newRec);
	if (result){
		printf("ERROR; return code from pthread_create() is %d\n", result);
	    exit(-1);
	}

	return newRec->taskID;
}


// a "wrapper" function that hides the complexity of the
// the pthread initialization. Ultimately, it just calls the programmer's
// start function.
static void *run(void *DirectReceiveTaskRef){

	DirectReceiveTask this = (DirectReceiveTask)DirectReceiveTaskRef;
	start(this);
	pthread_exit(NULL);
}


// The send method can be generated by the system since it always
// does the same thing
static void send(DirectReceiveTask this, Message data, int targetID){
	Comm->send(data, targetID);
}


#endif /* DIRECTRECEIVETASK_GENERATED_H_ */
