
#ifndef DATABASETASK_GENERATED_H_
#define DATABASETASK_GENERATED_H_


#include <stdio.h>
#include <pthread.h>


/******************************
 *  System generated code
 ******************************/

static void send(DatabaseTask this, Message data, int targetTaskID);
static void receive(DatabaseTask this, int targetTaskID);

static void *run(void *DatabaseTaskRef);
static void start(DatabaseTask this);


// The DatabaseTask "class"
struct DatabaseTask {

	// private data members
	pthread_t threadRef;
	int taskID;

};


// The DatabaseTask "constructor"
unsigned int DatabaseTask_create(){

	DatabaseTask newRec = malloc(sizeof(struct DatabaseTask));
	if(newRec == NULL)
		FatalError("Cannot allocate memory in DatabaseTask_create");

	newRec->taskID = Comm->getNextTaskID(Comm);
	Comm->createMsgQ(Comm, newRec->taskID);

	int result = pthread_create( &(newRec->threadRef), NULL, run, (void *)newRec);
	if (result){
		printf("ERROR; return code from pthread_create() is %d\n", result);
	    exit(-1);
	}

	return newRec->taskID;
}


// a "wrapper" function that hides the complexity of the
// the pthread initialization. Ultimately, it just calls the programmer's
// start function.
static void *run(void *DatabaseTaskRef){

	DatabaseTask this = (DatabaseTask)DatabaseTaskRef;
	start(this);
	pthread_exit(NULL);
}


// The send method can be generated by the system since it always
// does the same thing
static void send(DatabaseTask this, Message data, int targetTaskID){
	Comm->send(Comm, data, targetTaskID);
}


#endif /* DATABASETASK_GENERATED_H_ */
